### PR TITLE
fixed no-results-found on the Categories Page

### PR DESCRIPTION
**Pull request by poggy33**
Fixed correctly displaying no-results-found block on the Categories Page

### CODE REVIEW

**Review by nadraharr — APPROVED** [review]

**Review by zim89 — COMMENTED** [review]
There is no point in passing the setIsCategoryFound prop to CategoriesList. We receive data in the CategoriesList component. accordingly, if the response received an empty array, then we should display the NoResults component, not a list

**Comment by poggy33** [comment]
> There is no point in passing the setIsCategoryFound prop to CategoriesList. We receive data in the CategoriesList component. accordingly, if the response received an empty array, then we should display the NoResults component, not a list

it works correctly

**Comment by zim89** [comment]
The Categories component is not responsible for retrieving data, so why store the isCategoryFound state in it and pass props to the CategoriesList? This will lead to your CategoriesList component being re-rendered once again, which in turn can cause the data to be re-fetched and more. And this is how it will work in general - you can store this state on the main page and transfer props deep down to Categories ))) this is not a very optimized option

**Comment by zim89** [comment]
Moreover, the CategoriesList component is reusable, i.e. if you use it in another part of the application, then the question will arise - what kind of prop is this isCategoryFound and then you will always have to create the corresponding states in other components

**Review by zim89 — APPROVED** [review]

**Pull request merged**
